---
apiVersion: v1
kind: Service
metadata:
  name: webapp-color-darkblue
  namespace: python-webapps
  labels:
    app: webapp-color-darkblue
spec:
  selector:
    app: webapp-color-darkblue
  ports:
  - protocol: TCP
    targetPort: 8080
    name: http
    port: 8080
